version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - slim-network

  webserver:
    image: nginx:alpine
    container_name: slim_webserver
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - slim-network
    depends_on:
      - app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ./vendor/bin/phpunit --configuration phpunit.xml

networks:
  slim-network:
    driver: bridge
